version: '2'
services:
    web:
        build:
            context: .
            args:
                workdir: /itemapp
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/itemapp
            - ~/.ssh:/root/.ssh
        ports:
            - "3000:3000"
        volumes_from:
            - bundle
    bundle:
        image: itemapp_web
        volumes:
            - /bundle
